### ISSUE TITLE
Repository cannot be cloned

### ISSUE THREAD

**Issue by escamoteur** [gerryhigh/Flutter-Google-Maps-Demo#2]
Hi trying to clone the repo results in en error that it cannot check out because of the build\ios folder

```
fatal: cannot create directory at 'build\ios': No such file or directory
```

**Comment by gerryhigh** [comment]
I've had multiple people clone this repo so I'm not sure why it wouldn't work for you. This is on Windows?

**Comment by escamoteur** [comment]
Yep, I tried it with Github desktop
